[package]
name = "edge-net"
version = "0.5.0"
authors = ["Ivan Markov <ivan.markov@gmail.com>"]
edition = "2021"
categories = ["embedded", "hardware-support"]
keywords = ["embedded", "svc", "network"]
description = "no_std and no-alloc async implementations of various network protocols."
repository = "https://github.com/ivmarkov/edge-net"
license = "MIT OR Apache-2.0"
readme = "README.md"
rust-version = "1.71"

[features]
default = ["std"]

std = ["alloc", "embedded-io/std", "embassy-sync/std", "embedded-svc?/std", "async-io", "libc", "futures-lite/std", "httparse/std", "domain?/std"]
alloc = ["embedded-io/alloc", "embedded-svc?/alloc", "embedded-io-async?/alloc", ]
nightly = ["embedded-io-async", "embassy-sync/nightly", "embedded-svc?/nightly"]
embassy-util = [] # Just for backward compat. To be removed in future

[dependencies]
embedded-io = { version = "0.6", default-features = false }
embedded-io-async = { version = "0.6", default-features = false, optional = true }
heapless = { version = "0.7", default-features = false }
httparse = { version = "1.7", default-features = false }
num_enum = { version = "0.7", default-features = false }
embassy-futures = "0.1"
embassy-time = "0.1"
embassy-sync = "0.3"
no-std-net = { version = "0.6", default-features = false }
rand_core = "0.6"
log = { version = "0.4", default-features = false }
base64 = { version = "0.13", default-features = false }
sha1_smol = { version = "1", default-features = false }
embedded-nal-async = "0.6"
domain = { version = "0.7", default-features = false, optional = true }
futures-lite = { version = "1", default-features = false, optional = true }
async-io = { version = "2", default-features = false, optional = true }
libc = { version = "0.2", default-features = false, optional = true }
embedded-svc = { version = "0.26", default-features = false, optional = true, features = ["embedded-io-async"] }
rumqttc = { version = "0.19", optional = true }

[dev-dependencies]
anyhow = "1"
simple_logger="2.2"

[[example]]
name = "captive_portal"
required-features = ["std", "domain"]

[[example]]
name = "simple"
required-features = ["std", "nightly"]

[[example]]
name = "http_client"
required-features = ["std", "nightly"]

[[example]]
name = "http_server"
required-features = ["std", "nightly"]
